name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Create changelog
        run: |
          pnpm release
          git add .
          git diff --staged --exit-code || (git commit -m 'ci(changelog): added changelog' && git push)
